#' stan_ode_generate
#' @description Generates a syntactically valid Stan program using the ODE system generated by
#' \code{\link{stan_lines}}.
#' @param obj Output of \code{stan_lines}.
#' @param has_events A logical value that indicates whether or not the model contains events.
#' @param integrator The type of integrator to use. One of either \code{"rk45"} or \code{"bdf"}.
#' @param n_states Number of states in the ODE system. 
#' @return A string with the Stan model which can be used in \code{\link[rstan]{stan}}. A more
#' readable representation of the model can be constructed by applying the
#' \code{\link[base]{cat}} function to the output.
#' @param sampling Logical variable indicating whether the user wants to perform sampling.
#' @seealso \code{\link{stan_lines}}
#' @examples
#' \dontrun{
#' # Define the ODE system as an R function
#' two_cpt <- function(t, y, parms) {
#'   with(as.list(c(y, parms)), {
#'     dy_gut = -ka * y_gut
#'     dy_cent = ka * y_gut - (CL/V_cent + Q/V_cent) * y_cent + (Q/V_peri) * y_peri
#'     dy_peri = (Q/V_cent) * y_cent - (Q/V_peri) * y_peri
#'     return(list(c(dy_gut=dy_gut, dy_cent=dy_cent, dy_peri=dy_peri)))
#'   })
#' }
#' # Create the time steps, inital state values, and parameter values
#' pars <- c("CL" = 10, Q = 13, "V_cent" = 20, "V_peri" = 73, ka = 3)
#' yini <- c("y_gut" = 0, "y_cent" = 0, "y_peri" = 0)
#' time_steps <- seq(0, 150, by = 0.01)
#' # Convert the R defined ODE into Stan syntax
#' sl <- stan_lines(two_cpt, state = yini,
#'                  pars = pars,
#'                  times = time_steps)
#' # Generate the useable Stan file
#' cat(stan_ode_generate(sl, has_events = TRUE, integrator = "rk45", n_states = 3))
#' }           
#' @export

stan_ode_generate <- function(obj, has_events, integrator, n_states, sampling) {
  n_eqn <- length(obj)
  if (has_events == FALSE) {
    if (isTRUE(sampling)) {
      if (integrator == "rk45")
        path <- system.file(package = "rstanode", "ode_wrap_sampling_rk45.stan")
      else
        path <- system.file(package = "rstanode", "ode_wrap_sampling_bdf.stan") 
    }
    else {
      if (integrator == "rk45")
        path <- system.file(package = "rstanode", "ode_wrap_rk45.stan")
      else
        path <- system.file(package = "rstanode", "ode_wrap_bdf.stan") 
    }
  }
  else {
    if (integrator == "rk45")
      path <- system.file(package = "rstanode", "ode_wrap_events_rk45.stan")
    else
      path <- system.file(package = "rstanode", "ode_wrap_events_bdf.stan")
  }
  stan_wrapper <- readLines(path)
  
  sel <- which(stan_wrapper == "    #include \"user_func.stan\"")
  upr <- 1:(sel-1)
  lwr <- (sel+1):length(stan_wrapper)
  
  ode_eqns <- c("    // AUTO GENERATED CODE",
                paste0("    real dydt[",n_states,"];"),
                obj,
                "    return dydt;")
  out <- c(stan_wrapper[upr], ode_eqns, stan_wrapper[lwr])
  # tmp_fname <- tempfile(tmpdir = "", fileext = ".stan")
  # writeLines(out, paste0(getwd(), tmp_fname))
  # return(c(tmp_fname = tmp_fname))
  return(paste(out, collapse = "\n"))
}
