#' stan_ode_generate
#' @description Generates a stan program using the ODE system generated by
#' \code{stanode::stan_lines()}.
#' @param obj Output of \code{stan_lines()}.
#' @return A list with the stan model to use in \code{rstan::stan()} and more
#' visually appealing version to be used with \code{cat()}.
#' @export

stan_ode_generate <- function(obj) {
  n_eqn <- length(obj)
  path <- system.file(package = "stanode", "ode_wrap.stan")
  stan_wrapper <- readLines(path)
  
  sel <- which(stan_wrapper == "    #include \"user_func.stan\"")
  upr <- 1:(sel-1)
  lwr <- (sel+1):length(stan_wrapper)
  
  ode_eqns <- c("    // AUTO GENERATED CODE",
                paste0("    real dydt[",n_eqn,"];"),
                obj,
                "    return dydt;")
  out <- c(stan_wrapper[upr], ode_eqns, stan_wrapper[lwr])
  tmp_fname <- tempfile(tmpdir = "", fileext = ".stan")
  writeLines(out, paste0(getwd(), tmp_fname))
  return(c(tmp_fname = tmp_fname))
}
